apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aqua-kube-enforcer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aqua
  source:
    repoURL: 'https://github.com/semyonmor/aqua-helm'
    path: kube-enforcer
    targetRevision: '2022.4.71'
    helm:
      parameters:
        - name: certsSecret.autoGenerate
          value: 'true'
        - name: gateway.address
          value: aqua-lb
        - name: gateway.port
          value: '443'
        - name: starboard.OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT
          value: '2'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: aqua
  syncPolicy:
    automated:
      prune: true
      selfHeal: true